### PR TITLE
Handle extra repos

### LINKED ISSUE #3: Not respecting :mvn/repos?
Is it possible that this application doesn't include :mvn/repos in its operations? I have a few dependencies that are not hosted on maven central, so I add this line to my deps.edn:

```clojure
:mvn/repos {"ias-releases" {:url "https://maven.mangoautomation.net/repository/ias-release/"}}
```

This works doing REPL or other normal operations, but clj2nix says that it can't find these dependencies.

### PR DESCRIPTION
**Pull request by WhittlesJr**
Fixes #3

### CODE REVIEW

**Comment by WhittlesJr** [comment]
Er, wait, something's not right.

**Comment by WhittlesJr** [comment]
That should work

**Comment by hlolli** [comment]
This looks good to me. Easy ;)

Some clojure style-guide-ish stuff I may fix in the near future.

Also tools.deps api changed recently, I also need to account for that soon, as not to create different dependency resolution.

**Comment by WhittlesJr** [comment]
Thank you for the quick turnaround!

**Pull request merged**
